-- =====================================================
-- Golda Events CRM - Seed Data (Flavors)
-- Run AFTER schema.sql
-- =====================================================

-- Dairy Flavors
INSERT INTO public.flavors (name, category, is_in_stock, sort_order) VALUES
  ('מנגו עוגת גבינה', 'dairy', true, 1),
  ('שוקולד מריר ופטל', 'dairy', true, 2),
  ('אוכמניות כחולות עם שוקולד לבן', 'dairy', true, 3),
  ('עוגת סנת אונורה', 'dairy', true, 4),
  ('אפוגטו', 'dairy', true, 5),
  ('טרמיסו', 'dairy', true, 6),
  ('עוגת יום הולדת', 'dairy', true, 7),
  ('בייגלה קרמל מלוח', 'dairy', true, 8),
  ('וניל', 'dairy', true, 9),
  ('שוקולד', 'dairy', true, 10),
  ('פיסטוק', 'dairy', true, 11),
  ('שוקולד פיסטוק', 'dairy', true, 12),
  ('שוקלד לבן קרם פיסטוק', 'dairy', true, 13),
  ('חלבה פיסטוק', 'dairy', true, 14),
  ('בייגלה שוקולד חלב', 'dairy', true, 15),
  ('בייגלה שוקולד לבן', 'dairy', true, 16),
  ('סמורס', 'dairy', true, 17),
  ('שוקולד לבן ועוגיות', 'dairy', true, 18),
  ('קוקיז', 'dairy', true, 19),
  ('קרם עוגיות', 'dairy', true, 20),
  ('מרשמלו', 'dairy', true, 21),
  ('מסטיק', 'dairy', true, 22),
  ('היער השחור', 'dairy', true, 23),
  ('תותים בטעם מסקרפונה ריקוטה', 'dairy', true, 24),
  ('מקדמיה', 'dairy', true, 25),
  ('עוגת ביסקוויטים', 'dairy', true, 26),
  ('עוגיות קרמל בטעם עוגת גבינה', 'dairy', true, 27),
  ('פבלובה', 'dairy', true, 28),
  ('בננה וקרם עוגיות קרמל', 'dairy', true, 29),
  ('בננה ספליט', 'dairy', true, 30),
  ('בננה טופי', 'dairy', true, 31),
  ('מנטה', 'dairy', true, 32),
  ('קוקימן', 'dairy', true, 33),
  ('שוקלד קפה', 'dairy', true, 34),
  ('וופל נוגט', 'dairy', true, 35),
  ('קרם שוקלד ואגוזי לוז', 'dairy', true, 36),
  ('מוס אגוזי לוז', 'dairy', true, 37),
  ('אגוזי לוז שלמים ושוקולד', 'dairy', true, 38),
  ('אגוזי לוז שלמים ושוקולד לבן', 'dairy', true, 39),
  ('פאי פקאן', 'dairy', true, 40),
  ('קרמשניט', 'dairy', true, 41),
  ('קרמל מלוח', 'dairy', true, 42),
  ('קשיו מלוח', 'dairy', true, 43),
  ('שוקולד מלוח', 'dairy', true, 44),
  ('שוקולד לבן קוקוס ושקדים', 'dairy', true, 45),
  ('שוקולד שקדים וקרמל', 'dairy', true, 46),
  ('בלונדי שקדים', 'dairy', true, 47),
  ('חמאת בוטנים ושוקולד מריר', 'dairy', true, 48),
  ('קפה ושוקולד', 'dairy', true, 49),
  ('סטרצ''טלה', 'dairy', true, 50),
  ('עוגת גבינה קרמבל חמאה', 'dairy', true, 51),
  ('קרם ברולה קרמבל פיסטוק', 'dairy', true, 52),
  ('קרמבל פטל ושוקולד לבן', 'dairy', true, 53),
  ('פאי לימון', 'dairy', true, 54),
  ('קדאיף שוקולד פיסטוק', 'dairy', true, 55),
  ('קרם גלולית חומה', 'dairy', true, 56),
  ('קרם גלולית לבנה', 'dairy', true, 57),
  ('קפה לייט', 'dairy', true, 58),
  ('וניל לייט', 'dairy', true, 59);

-- Parve Flavors
INSERT INTO public.flavors (name, category, is_in_stock, sort_order) VALUES
  ('קוקוס', 'parve', true, 1),
  ('בננה', 'parve', true, 2),
  ('תמר', 'parve', true, 3),
  ('לימונצלו', 'parve', true, 4),
  ('אבטיח נענע', 'parve', true, 5),
  ('תות', 'parve', true, 6),
  ('פירות יער', 'parve', true, 7),
  ('אוכמניות וליצ''י', 'parve', true, 8),
  ('אננס', 'parve', true, 9),
  ('מנגו', 'parve', true, 10),
  ('טרופי', 'parve', true, 11),
  ('שוקולד מריר', 'parve', true, 12),
  ('בייגלה מריר', 'parve', true, 13),
  ('מוס קרם עוגיות טבעוני', 'parve', true, 14),
  ('מוס קרם עוגיות קרמל טבעוני', 'parve', true, 15);
